#!/usr/bin/env python3
"""Generate upstream version mapping table for README-loongsuite.rst."""

from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path
from typing import Any

BEGIN_MARKER = ".. BEGIN AUTO-GENERATED VERSION MAPPING"
END_MARKER = ".. END AUTO-GENERATED VERSION MAPPING"


def _load_mapping(mapping_path: Path) -> dict[str, Any]:
    with mapping_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _format_cell(value: Any) -> str:
    if value is None:
        return "-"
    text = str(value).strip()
    return text if text else "-"


def _render_generated_block(data: dict[str, Any], generated_at: str) -> str:
    component = _format_cell(data.get("component"))
    upstream_repo = _format_cell(data.get("upstream_repository"))
    upstream_path = _format_cell(data.get("upstream_path"))
    schema_version = _format_cell(data.get("schema_version"))
    mappings = data.get("mappings", [])

    lines: list[str] = []
    lines.append(BEGIN_MARKER)
    lines.append(
        ".. This section is generated by scripts/generate_version_mapping_table.py"
    )
    lines.append("")
    lines.append(f"- 组件: ``{component}``")
    lines.append(f"- 上游仓库: ``{upstream_repo}``")
    lines.append(f"- 上游路径: ``{upstream_path}``")
    lines.append(f"- 映射格式版本: ``{schema_version}``")
    lines.append(f"- 生成时间(UTC): ``{generated_at}``")
    lines.append("")
    lines.append(".. list-table:: 版本映射")
    lines.append("   :header-rows: 1")
    lines.append("")
    lines.append("   * - LoongSuite 版本")
    lines.append("     - OTel util-genai 版本")
    lines.append("     - OTel commit")
    lines.append("     - 上游来源")
    lines.append("     - 同步日期")
    lines.append("     - 说明")

    if not mappings:
        lines.append("   * - -")
        lines.append("     - -")
        lines.append("     - -")
        lines.append("     - -")
        lines.append("     - -")
        lines.append("     - -")
    else:
        for item in mappings:
            source = f"{_format_cell(item.get('upstream_ref_type'))}:{_format_cell(item.get('upstream_ref'))}"
            lines.append(
                f"   * - ``{_format_cell(item.get('loongsuite_version'))}``"
            )
            lines.append(
                f"     - ``{_format_cell(item.get('upstream_version'))}``"
            )
            lines.append(
                f"     - ``{_format_cell(item.get('upstream_commit'))}``"
            )
            lines.append(f"     - ``{source}``")
            lines.append(f"     - ``{_format_cell(item.get('sync_date'))}``")
            lines.append(f"     - {_format_cell(item.get('notes'))}")

    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def _upsert_generated_block(readme_content: str, block: str) -> str:
    if BEGIN_MARKER in readme_content and END_MARKER in readme_content:
        before, rest = readme_content.split(BEGIN_MARKER, 1)
        _, after = rest.split(END_MARKER, 1)
        return f"{before}{block}{after}"

    if not readme_content.endswith("\n"):
        readme_content += "\n"

    section = (
        "\n版本映射（自动生成）\n"
        "---------------------\n\n"
        "以下内容由 ``scripts/generate_version_mapping_table.py`` 根据\n"
        "``upstream_version_map.json`` 自动生成，请不要手动编辑该区块。\n\n"
        f"{block}\n"
    )
    return readme_content + section


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mapping",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "upstream_version_map.json",
        help="Path to upstream version mapping JSON file.",
    )
    parser.add_argument(
        "--readme",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "README-loongsuite.rst",
        help="Path to README-loongsuite.rst file.",
    )
    args = parser.parse_args()

    data = _load_mapping(args.mapping)
    generated_at = (
        dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    )
    block = _render_generated_block(data, generated_at)

    readme_content = args.readme.read_text(encoding="utf-8")
    updated_content = _upsert_generated_block(readme_content, block)
    args.readme.write_text(updated_content, encoding="utf-8")


if __name__ == "__main__":
    main()
